<?php

namespace Database\Seeders;

use App\Models\Faq;
use Illuminate\Database\Seeder;

class FaqSeeder extends Seeder
{
    public function run(): void
    {
        $faqs = [
            ['question' => 'What types of custom software do you develop?',         'answer' => 'We develop a wide range of custom software solutions including enterprise resource planning (ERP) systems, customer relationship management (CRM) tools, inventory management systems, and bespoke business applications tailored to your specific needs and workflows.', 'product_name' => 'software-it',           'is_visible_home' => true,  'order' => 1],
            ['question' => 'Do you provide ongoing support after development?',     'answer' => 'Yes, we offer comprehensive post-development support including maintenance, updates, bug fixes, and feature enhancements. We provide different support packages to ensure your software continues to perform optimally.', 'product_name' => 'software-it',           'is_visible_home' => true,  'order' => 2],
            ['question' => 'What technologies do you use for mobile app development?','answer' => 'We use both native (Swift for iOS, Kotlin for Android) and cross-platform technologies (React Native, Flutter) depending on your project requirements, budget, and performance needs.', 'product_name' => 'software-it',           'is_visible_home' => false, 'order' => 3],
            ['question' => 'How does Bulk SMS marketing work?',                     'answer' => 'Our Bulk SMS service allows you to send promotional or transactional messages to thousands of customers simultaneously. We provide a user-friendly platform, API integration, and advanced features like DND filtering and delivery reports.', 'product_name' => 'social-media',          'is_visible_home' => true,  'order' => 4],
            ['question' => 'What is WhatsApp Marketing Suite?',                     'answer' => 'Our WhatsApp Marketing Suite includes promotional messaging, chatbot automation, Meta Verified services, and personal number integration. It helps businesses engage customers directly on WhatsApp with high open rates and better engagement.', 'product_name' => 'social-media',          'is_visible_home' => true,  'order' => 5],
            ['question' => 'Can you help with content creation for social media?',  'answer' => 'Yes, we offer complete content creation services including podcast production, reel shoots, product photography, and graphic design to ensure your social media presence is engaging and professional.', 'product_name' => 'social-media',          'is_visible_home' => false, 'order' => 6],
            ['question' => 'How long does it take to see SEO results?',             'answer' => 'SEO is a long-term strategy. Typically, you can see initial improvements in 3-6 months, with significant results appearing in 6-12 months. The timeline depends on your industry competition, website age, and the current state of your SEO.', 'product_name' => 'seo',                  'is_visible_home' => true,  'order' => 7],
            ['question' => "What's the difference between Local SEO and International SEO?", 'answer' => 'Local SEO focuses on optimizing your online presence to attract customers from specific geographic locations, while International SEO targets multiple countries and languages, involving hreflang tags, country-specific domains, and international keyword research.', 'product_name' => 'seo',                  'is_visible_home' => true,  'order' => 8],
            ['question' => 'Do you provide SEO audit reports?',                     'answer' => 'Yes, we conduct comprehensive SEO audits that analyze technical SEO, on-page optimization, backlink profile, content quality, and competitor analysis. You receive detailed reports with actionable recommendations.', 'product_name' => 'seo',                  'is_visible_home' => false, 'order' => 9],
            ['question' => 'What is your website development process?',             'answer' => 'Our process includes discovery and planning, design mockups, development, testing, and deployment. We follow agile methodology with regular client updates and feedback sessions throughout the project.', 'product_name' => 'design-dev',           'is_visible_home' => true,  'order' => 10],
            ['question' => 'Do you create responsive websites?',                    'answer' => 'Absolutely. All our websites are fully responsive and optimized for all devices - desktop, tablet, and mobile. We ensure seamless user experience across all screen sizes and browsers.', 'product_name' => 'design-dev',           'is_visible_home' => true,  'order' => 11],
            ['question' => 'What e-commerce platforms do you work with?',           'answer' => 'We work with various e-commerce platforms including Shopify, WooCommerce, Magento, and custom solutions. We help you choose the best platform based on your business needs and budget.', 'product_name' => 'design-dev',           'is_visible_home' => false, 'order' => 12],
            ['question' => 'What does content marketing strategy include?',         'answer' => 'Our content marketing strategy includes audience research, content planning, keyword strategy, content calendar, distribution plan, and performance metrics. We create content that resonates with your target audience and drives conversions.', 'product_name' => 'content-marketing',    'is_visible_home' => true,  'order' => 13],
            ['question' => 'How do you measure content marketing success?',         'answer' => 'We track multiple metrics including website traffic, engagement rates, time on page, social shares, lead generation, conversion rates, and ROI. Regular reports help us optimize your content strategy.', 'product_name' => 'content-marketing',    'is_visible_home' => false, 'order' => 14],
            ['question' => 'What is your approach to PPC advertising?',             'answer' => 'We create data-driven PPC campaigns focusing on keyword research, audience targeting, ad copy optimization, landing page design, and continuous A/B testing to maximize your return on ad spend.', 'product_name' => 'performance-marketing','is_visible_home' => true,  'order' => 15],
            ['question' => 'How do you improve conversion rates?',                  'answer' => 'We use CRO techniques including user behavior analysis, A/B testing, heatmaps, session recordings, and landing page optimization to identify and fix conversion barriers, ultimately increasing your conversion rates.', 'product_name' => 'performance-marketing','is_visible_home' => true,  'order' => 16],
            ['question' => 'Do you manage Amazon and YouTube advertising?',         'answer' => 'Yes, we manage comprehensive advertising campaigns on Amazon (Sponsored Products, Brands) and YouTube (TrueView, Bumper ads) to help you reach customers on these high-traffic platforms effectively.', 'product_name' => 'performance-marketing','is_visible_home' => false, 'order' => 17],
            ['question' => 'What is your pricing model?',                           'answer' => 'We offer flexible pricing models including project-based pricing for one-time projects, monthly retainers for ongoing services, and performance-based pricing for certain marketing services. We provide custom quotes based on your specific requirements.', 'product_name' => 'general',             'is_visible_home' => true,  'order' => 18],
            ['question' => 'How do I get started with your services?',              'answer' => 'Getting started is easy! Contact us for a free consultation where we discuss your goals, analyze your needs, and provide a customized proposal. Once approved, we begin the onboarding process and kick off your project.', 'product_name' => 'general',             'is_visible_home' => true,  'order' => 19],
            ['question' => 'Do you work with businesses of all sizes?',             'answer' => 'Yes, we work with startups, small businesses, medium enterprises, and large corporations across various industries. We tailor our services to meet the specific needs and budgets of each client.', 'product_name' => 'general',             'is_visible_home' => true,  'order' => 20],
        ];

        foreach ($faqs as $data) {
            Faq::firstOrCreate(['question' => $data['question']], array_merge($data, ['is_active' => true]));
        }

        $this->command->info('FaqSeeder: seeded ' . count($faqs) . ' FAQs.');
    }
}
