<?php

namespace Database\Seeders;

use App\Models\PageSeo;
use Illuminate\Database\Seeder;

class PageSeoSeeder extends Seeder
{
    public function run(): void
    {
        $entries = array_merge(
            $this->pages(),
            $this->products(),
            $this->softwareServices(),
            $this->digitalMarketingServices(),
        );

        foreach ($entries as $entry) {
            PageSeo::updateOrCreate(['page_key' => $entry['page_key']], $entry);
        }
    }

    // ─── Group: page ──────────────────────────────────────────────────────────

    private function pages(): array
    {
        $group       = 'page';
        $groupLabel  = 'Pages';

        return [
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 1,
                'page_key'    => 'home',
                'label'       => 'Home',
                'title'       => 'Software & Digital Marketing Company in Nashik | RichSol',
                'description' => "Rich System Solutions — Nashik's leading IT company since 2009. Custom software, website development, digital marketing, bulk SMS & Meta Verified WhatsApp API. Get a free demo today!",
                'keywords'    => 'software development company Nashik, IT company Nashik Maharashtra, digital marketing agency Nashik, custom software development Nashik, website development Nashik, bulk SMS service Nashik, WhatsApp Business API Nashik, mobile app development Nashik, SEO services Nashik, web development Nashik, IT training Nashik, software internship Nashik, digital marketing services Maharashtra, IVR system provider Nashik, business communication solutions, Rich System Solutions',
                'canonical'   => '/',
                'og_image'    => '/og-home.jpg',
                'h1'          => 'Software Development & Digital Marketing Company in Nashik',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 2,
                'page_key'    => 'about',
                'label'       => 'About',
                'title'       => 'About Us | 16+ Years IT Experience in Nashik | Rich System Solutions',
                'description' => "Learn about Rich System Solutions — Nashik's trusted IT company since 2009. 16+ years of software development, digital marketing & business communication experience across Maharashtra.",
                'keywords'    => 'about Rich System Solutions, IT company Nashik since 2009, software company Nashik 16 years, Gauri Joshi Rich System Solutions, digital solutions company Nashik, technology partner Maharashtra, experienced IT firm Nashik, software development company profile Nashik',
                'canonical'   => '/about',
                'og_image'    => '/og-about.jpg',
                'h1'          => "About Rich System Solutions — Nashik's Trusted IT Partner Since 2009",
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 3,
                'page_key'    => 'services',
                'label'       => 'Services',
                'title'       => 'IT & Digital Marketing Services in Nashik | Rich System Solutions',
                'description' => 'Complete IT and business services: software development, digital marketing, bulk SMS, WhatsApp API, IVR systems & IT training. Serving Nashik and Maharashtra businesses since 2009.',
                'keywords'    => 'IT services Nashik, business services Maharashtra, bulk SMS services, whatsapp services, digital automation, software services Nashik, complete business solutions Maharashtra, digital communication services, business technology solutions Nashik',
                'canonical'   => '/services',
                'og_image'    => '/og-services.jpg',
                'h1'          => 'Complete IT & Digital Marketing Services in Nashik, Maharashtra',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 4,
                'page_key'    => 'products',
                'label'       => 'Products',
                'title'       => 'Digital Communication Products | Bulk SMS, WhatsApp API & More | Nashik',
                'description' => 'Explore our digital products: Bulk SMS, Bulk Voice, WhatsApp Business API (Meta Verified), IVR System, Chatbot, and marketing automation tools. Trusted by 500+ businesses in Maharashtra.',
                'keywords'    => 'digital communication products, bulk SMS platform, WhatsApp Business API, IVR system, voice broadcasting, SMS marketing tool, WhatsApp chatbot, digital automation, business messaging solutions, alert notification system Nashik',
                'canonical'   => '/products',
                'og_image'    => '/og-products.jpg',
                'h1'          => 'Digital Communication Products for Nashik & Maharashtra Businesses',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 5,
                'page_key'    => 'softwareIT',
                'label'       => 'Software & IT Services',
                'title'       => 'Software Development Company in Nashik & India | IT Services | RichSol',
                'description' => 'Top software development company in Nashik — custom software, website development, mobile apps, UI/UX, e-commerce, cloud solutions & API integration. Get a free consultation today!',
                'keywords'    => 'software development company Nashik, custom software development Nashik, web development company Nashik, mobile app development Nashik, IT services Nashik, software company in Nashik Maharashtra, website development company Nashik, ecommerce development Nashik, React Next.js developer Nashik',
                'canonical'   => '/software-it-services',
                'og_image'    => '/og-software.jpg',
                'h1'          => 'Software Development Company in Nashik — Custom Software & Web Solutions',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 6,
                'page_key'    => 'digitalMarketingServices',
                'label'       => 'Digital Marketing Services',
                'title'       => 'Digital Marketing Agency in Nashik | SEO, PPC & Social Media',
                'description' => 'Full-service digital marketing agency in Nashik — SEO, social media marketing, PPC, content marketing, WhatsApp marketing & graphic design. Grow your business online with proven strategies.',
                'keywords'    => 'digital marketing agency Nashik, SEO services Nashik Maharashtra, social media marketing Nashik, PPC advertising Nashik, digital marketing company Maharashtra, online marketing Nashik, Google Ads Nashik, Instagram marketing Nashik, content marketing Nashik, WhatsApp marketing Nashik',
                'canonical'   => '/digital-marketing-services',
                'og_image'    => '/og-digital-marketing.jpg',
                'h1'          => 'Digital Marketing Agency in Nashik — SEO, Social Media & More',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 7,
                'page_key'    => 'resources',
                'label'       => 'Resources',
                'title'       => 'Resources | Digital Marketing Guides, IT Blogs & Career Opportunities',
                'description' => 'Access expert blogs, how-to guides, FAQs, and career opportunities from Rich System Solutions. Learn digital marketing, software development & IT best practices for Maharashtra businesses.',
                'keywords'    => 'digital marketing resources Nashik, IT blog Maharashtra, software development guides, career opportunities Nashik, IT jobs Nashik, digital marketing tutorials, how to guide software, FAQ digital marketing, Rich System Solutions blog',
                'canonical'   => '/resources',
                'og_image'    => '/og-resources.jpg',
                'h1'          => 'Resources — IT Blogs, Guides & Career Opportunities',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 8,
                'page_key'    => 'blog',
                'label'       => 'Blog',
                'title'       => 'Blog | Digital Marketing, Software & IT Insights | Rich System Solutions',
                'description' => 'Read expert blogs on digital marketing trends, bulk SMS strategies, WhatsApp API, software development & IT solutions for Nashik and Maharashtra businesses. Updated monthly.',
                'keywords'    => 'digital marketing blog Nashik, IT blog Maharashtra, bulk SMS tips, WhatsApp API guide, software development blog, SEO strategies 2025, digital marketing trends, IT insights Nashik, business technology blog Maharashtra',
                'canonical'   => '/resources/blog',
                'og_image'    => '/og-blog.jpg',
                'h1'          => 'Digital Marketing & Software Development Blog',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 9,
                'page_key'    => 'career',
                'label'       => 'Career',
                'title'       => 'IT Jobs & Career Opportunities in Nashik | Rich System Solutions',
                'description' => "Join Rich System Solutions in Nashik! We're hiring software developers, digital marketing executives, and communication specialists. Grow your IT career in Maharashtra.",
                'keywords'    => 'IT jobs Nashik, software developer jobs Nashik, digital marketing jobs Nashik Maharashtra, career opportunities IT company Nashik, software company jobs Nashik, web developer job Nashik, digital marketing executive job Maharashtra, tech jobs Nashik 2025',
                'canonical'   => '/resources/career',
                'og_image'    => '/og-career.jpg',
                'h1'          => 'IT Career Opportunities in Nashik — Join Our Team',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 10,
                'page_key'    => 'howToGuide',
                'label'       => 'How-To Guide',
                'title'       => 'How-To Guides | Digital Marketing & Software Tutorials for Businesses',
                'description' => 'Step-by-step guides for using bulk SMS, WhatsApp Business API, digital marketing strategies, and software tools. Practical tutorials for Nashik and Maharashtra businesses.',
                'keywords'    => 'how to use bulk SMS, WhatsApp Business API guide, digital marketing how to, software development tutorials, SEO guide for businesses Nashik, SMS marketing tutorial Maharashtra, WhatsApp chatbot setup guide, IT how to guides',
                'canonical'   => '/resources/how-to-guide',
                'og_image'    => '/og-howto.jpg',
                'h1'          => 'How-To Guides for Digital Marketing & Software Solutions',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 11,
                'page_key'    => 'faq',
                'label'       => 'FAQ',
                'title'       => 'FAQ | Frequently Asked Questions | Rich System Solutions Nashik',
                'description' => 'Got questions? Find answers about our software development, digital marketing, bulk SMS, WhatsApp API, IVR systems, pricing, and IT training services in Nashik and Maharashtra.',
                'keywords'    => 'FAQ Rich System Solutions, software development questions, bulk SMS FAQ, WhatsApp API FAQ, digital marketing questions, IT services FAQ Nashik, pricing software development, IVR system questions, website development FAQ Nashik',
                'canonical'   => '/resources/faq',
                'og_image'    => '/og-faq.jpg',
                'h1'          => 'Frequently Asked Questions — Rich System Solutions',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 12,
                'page_key'    => 'contact',
                'label'       => 'Contact',
                'title'       => 'Contact Us | Get a Free Quote | Rich System Solutions Nashik',
                'description' => 'Contact Rich System Solutions in Nashik for software development, digital marketing, bulk SMS or WhatsApp API services. Call +91 95959 02006 or request a free quote today.',
                'keywords'    => 'contact Rich System Solutions, IT company contact Nashik, software company Nashik phone, digital marketing agency contact Maharashtra, get free quote software development, call IT company Nashik, schedule demo software Nashik, Rich System Solutions address Tilakwadi',
                'canonical'   => '/contactus',
                'og_image'    => '/og-contact.jpg',
                'h1'          => 'Contact Rich System Solutions — Get Your Free Quote',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 13,
                'page_key'    => 'internship',
                'label'       => 'Internship',
                'title'       => 'IT Internship Program in Nashik | Learn Software & Digital Marketing',
                'description' => "Join Rich System Solutions' internship program in Nashik! Hands-on training in software development, digital marketing, bulk SMS & WhatsApp marketing. Build your IT career in Maharashtra.",
                'keywords'    => 'IT internship Nashik, software internship Nashik Maharashtra, digital marketing internship Nashik, web development training Nashik, learn software development Nashik, IT training program Nashik, technology internship Maharashtra, coding internship Nashik 2025',
                'canonical'   => '/internship',
                'og_image'    => '/og-internship.jpg',
                'h1'          => 'IT Internship Program in Nashik — Software & Digital Marketing Training',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 14,
                'page_key'    => 'scheduleademo',
                'label'       => 'Schedule a Demo',
                'title'       => 'Schedule a Free Demo | See Our Software & Digital Marketing Services',
                'description' => 'Book a free demo with Rich System Solutions. See how our custom software, bulk SMS, WhatsApp API or digital marketing services can grow your Nashik or Maharashtra business.',
                'keywords'    => 'schedule demo Rich System Solutions, free demo software Nashik, book demo digital marketing, WhatsApp API demo, bulk SMS demo, software consultation Nashik, free IT consultation Maharashtra, demo booking Rich System Solutions',
                'canonical'   => '/schedule-a-demo',
                'og_image'    => '/og-demo.jpg',
                'h1'          => 'Schedule a Free Demo with Rich System Solutions',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 15,
                'page_key'    => 'aiAutomation',
                'label'       => 'AI Automation',
                'title'       => 'AI Automation Services | Business Process Automation | Nashik',
                'description' => 'Automate business processes with AI-powered solutions from Rich System Solutions in Nashik. Intelligent chatbots, workflow automation, machine learning & smart business tools.',
                'keywords'    => 'AI automation Nashik, business process automation Maharashtra, AI chatbot Nashik, workflow automation software, intelligent automation Nashik, machine learning solutions, smart business automation, digital automation Nashik',
                'canonical'   => '/ai-automation',
                'og_image'    => '/og-ai.jpg',
                'h1'          => 'AI & Business Automation Services in Nashik, Maharashtra',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 16,
                'page_key'    => 'login',
                'label'       => 'Login',
                'title'       => 'Client Login | Portal Access | Rich System Solutions',
                'description' => 'Login to your Rich System Solutions client portal to manage campaigns, track SMS delivery, monitor digital marketing performance, and access reports.',
                'keywords'    => 'client portal login, Rich System Solutions login, SMS campaign dashboard, digital marketing portal, client access Nashik',
                'canonical'   => '/login',
                'og_image'    => '/og-login.jpg',
                'h1'          => 'Client Portal Login',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 17,
                'page_key'    => 'notFound',
                'label'       => 'Not Found (404)',
                'title'       => 'Page Not Found | Rich System Solutions',
                'description' => "The page you're looking for doesn't exist. Return to our homepage for software development and digital marketing services in Nashik.",
                'keywords'    => null,
                'canonical'   => '/404',
                'og_image'    => '/og-404.jpg',
                'h1'          => 'Page Not Found',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 18,
                'page_key'    => 'privacyPolicy',
                'label'       => 'Privacy Policy',
                'title'       => 'Privacy Policy | Rich System Solutions',
                'description' => 'Read the privacy policy of Rich System Solutions Pvt Ltd. We are committed to protecting your personal information and data security.',
                'keywords'    => 'privacy policy, data security, personal information, Rich System Solutions',
                'canonical'   => '/privacy-policy',
                'og_image'    => '/og-richsol-nashik.jpg',
                'h1'          => 'Privacy Policy — Rich System Solutions',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 19,
                'page_key'    => 'termsConditions',
                'label'       => 'Terms & Conditions',
                'title'       => 'Terms & Conditions | Rich System Solutions',
                'description' => "Read the terms and conditions for using Rich System Solutions' software, digital marketing, and communication services. Understanding your rights and obligations.",
                'keywords'    => 'terms conditions, service agreement, usage policy, Rich System Solutions',
                'canonical'   => '/terms-conditions',
                'og_image'    => '/og-richsol-nashik.jpg',
                'h1'          => 'Terms & Conditions — Rich System Solutions',
                'breadcrumb'  => null,
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 20,
                'page_key'    => 'industries',
                'label'       => 'Industries',
                'title'       => 'Industries We Serve | IT Solutions for Every Sector | Nashik',
                'description' => 'Rich System Solutions serves all industries in Nashik and Maharashtra — manufacturing, healthcare, education, retail, real estate, hospitality, and more.',
                'keywords'    => 'industries served Nashik, IT solutions healthcare Nashik, manufacturing software Maharashtra, education technology Nashik, retail digital marketing, hospitality IT solutions Nashik',
                'canonical'   => '/industries',
                'og_image'    => '/og-industries.jpg',
                'h1'          => 'Industries We Serve Across Nashik & Maharashtra',
                'breadcrumb'  => null,
            ],
        ];
    }

    // ─── Group: product ───────────────────────────────────────────────────────

    private function products(): array
    {
        $group      = 'product';
        $groupLabel = 'Products';

        return [
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 1,
                'page_key'    => 'bulkSMS',
                'label'       => 'Bulk SMS',
                'title'       => 'Bulk SMS Service in Nashik | Promotional & Transactional SMS',
                'description' => 'Reliable bulk SMS service in Nashik for marketing, OTP, and alerts. Reach thousands instantly with 98%+ open rates. Trusted by 500+ Maharashtra businesses. Free trial available!',
                'keywords'    => 'bulk SMS Nashik, bulk SMS service Maharashtra, promotional SMS Nashik, transactional SMS service, OTP SMS provider Nashik, SMS marketing Nashik, mass text messaging Maharashtra, bulk SMS platform India, affordable SMS service Nashik',
                'canonical'   => '/products/bulk-sms',
                'og_image'    => '/og-bulk-sms.jpg',
                'h1'          => 'Bulk SMS Service in Nashik — Promotional, Transactional & OTP',
                'breadcrumb'  => 'Bulk SMS Services',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 2,
                'page_key'    => 'bulkVoice',
                'label'       => 'Bulk Voice',
                'title'       => 'Bulk Voice Call Service Provider India | Auto Dialer | RichSol',
                'description' => 'Professional bulk voice messaging in Nashik for customer alerts, campaigns & announcements. High delivery, vernacular language support. Ideal for Nashik MIDC businesses.',
                'keywords'    => 'bulk voice Nashik, voice broadcasting Maharashtra, bulk voice call service, voice message blast Nashik, IVR voice call, bulk phone call service Maharashtra, audio alert system Nashik, voice campaign service India',
                'canonical'   => '/products/bulk-voice',
                'og_image'    => '/og-bulk-voice.jpg',
                'h1'          => 'Bulk Voice Call Service in Nashik & Maharashtra',
                'breadcrumb'  => 'Bulk Voice Services',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 3,
                'page_key'    => 'whatsappService',
                'label'       => 'WhatsApp Service',
                'title'       => 'WhatsApp Business API Provider India | Meta Verified | RichSol',
                'description' => 'Official Meta Verified WhatsApp Business API in Nashik. Send bulk WhatsApp messages, automate customer support & run campaigns. Trusted provider in Maharashtra. Get started today!',
                'keywords'    => 'WhatsApp Business API Nashik, Meta verified WhatsApp provider Nashik, bulk WhatsApp Nashik Maharashtra, official WhatsApp API India, WhatsApp marketing Nashik, WhatsApp for business Nashik, WhatsApp Business API Maharashtra, WhatsApp API reseller Nashik',
                'canonical'   => '/products/whatsapp-service',
                'og_image'    => '/og-whatsapp-service.jpg',
                'h1'          => 'WhatsApp Business API in Nashik — Meta Verified Provider',
                'breadcrumb'  => 'WhatsApp Business Services',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 4,
                'page_key'    => 'digitalMarketing',
                'label'       => 'Digital Marketing (Product)',
                'title'       => 'Digital Marketing Services in Nashik | Grow Your Business Online',
                'description' => 'Complete digital marketing services in Nashik — SEO, social media, PPC, content & email marketing. Get more leads and grow your Maharashtra business online. Free strategy consultation.',
                'keywords'    => 'digital marketing Nashik, online marketing agency Nashik, SEO company Nashik, social media marketing Nashik Maharashtra, digital marketing for MIDC businesses, lead generation Nashik, Google Ads Nashik, Instagram ads Maharashtra',
                'canonical'   => '/products/digital-marketing',
                'og_image'    => '/og-digital-marketing-service.jpg',
                'h1'          => 'Digital Marketing Services in Nashik, Maharashtra',
                'breadcrumb'  => 'Digital Marketing Services',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 5,
                'page_key'    => 'whatsappChatbot',
                'label'       => 'WhatsApp Chatbot',
                'title'       => 'WhatsApp Marketing Software & Chatbot for Business | RichSol',
                'description' => 'Intelligent WhatsApp chatbots for Nashik businesses. Automate customer service, qualify leads, and run 24/7 support on WhatsApp. Powered by AI, deployed in days. Free demo available.',
                'keywords'    => 'WhatsApp chatbot Nashik, chat automation Maharashtra, AI chatbot WhatsApp, WhatsApp bot Nashik, customer service bot Maharashtra, automated WhatsApp responses, chatbot for business Nashik, WhatsApp automation service',
                'canonical'   => '/products/whats-chatbot',
                'og_image'    => '/og-whatsapp-chatbot.jpg',
                'h1'          => 'WhatsApp Chatbot Solutions for Nashik & Maharashtra Businesses',
                'breadcrumb'  => 'WhatsApp Chatbot Solutions',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 6,
                'page_key'    => 'digitalAutomation',
                'label'       => 'Digital Automation',
                'title'       => 'Business Automation Services India | Digital Automation | RichSol',
                'description' => 'Automate your business processes in Nashik with our digital automation solutions. Streamline marketing, sales, and customer communication workflows for better efficiency and ROI.',
                'keywords'    => 'digital automation Nashik, workflow automation Maharashtra, business process automation, marketing automation Nashik, sales automation Maharashtra, CRM automation Nashik, digital workflow software, process automation services India',
                'canonical'   => '/products/digital-auto',
                'og_image'    => '/og-digital-auto.jpg',
                'h1'          => 'Digital Business Automation Solutions in Nashik',
                'breadcrumb'  => 'Digital Automation Solutions',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 7,
                'page_key'    => 'designDevelopment',
                'label'       => 'Design & Development',
                'title'       => 'Website Design & Development in Nashik | Professional Web Agency',
                'description' => 'Professional website design and development in Nashik. Responsive websites, landing pages, and web applications built to rank on Google and convert visitors to customers.',
                'keywords'    => 'website design Nashik, web development Nashik Maharashtra, professional web design, responsive website Nashik, landing page design, web application development Nashik, website for business Nashik, affordable web design Maharashtra',
                'canonical'   => '/products/design-develop',
                'og_image'    => '/og-design-develop.jpg',
                'h1'          => 'Website Design & Development Services in Nashik',
                'breadcrumb'  => 'Design & Development Services',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 8,
                'page_key'    => 'graphicDesign',
                'label'       => 'Graphic Design (Product)',
                'title'       => 'Graphic Design Agency in Nashik | Logo & Brand Design | RichSol',
                'description' => 'Creative graphic design services in Nashik — logo design, brand identity, brochures, social media creatives & marketing materials. Professional designers, fast turnaround.',
                'keywords'    => 'graphic design Nashik, logo design Nashik Maharashtra, branding services Nashik, social media design, creative agency Nashik, marketing materials design, brand identity Nashik, poster design Nashik, digital design Maharashtra',
                'canonical'   => '/products/graphic-design',
                'og_image'    => '/og-graphic-design.jpg',
                'h1'          => 'Graphic Design Services in Nashik — Logo, Branding & Creatives',
                'breadcrumb'  => 'Graphic Design Services',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 9,
                'page_key'    => 'alertSystem',
                'label'       => 'Alert System',
                'title'       => 'Bulk SMS Service Provider in India | DLT-Compliant | RichSol',
                'description' => 'Real-time automated alert systems for Nashik businesses. Send instant alerts via SMS, WhatsApp, voice & email. Ideal for schools, hospitals, factories & enterprises in Maharashtra.',
                'keywords'    => 'alert system Nashik, notification system Maharashtra, real-time alerts business Nashik, automated alerts SMS WhatsApp, school alert system Nashik, hospital notification system, factory alert system MIDC, business alerts Maharashtra',
                'canonical'   => '/products/alert-system',
                'og_image'    => '/og-alert-system.jpg',
                'h1'          => 'Automated Alert & Notification System in Nashik',
                'breadcrumb'  => 'Alert System Solutions',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 10,
                'page_key'    => 'ivrSystem',
                'label'       => 'IVR System',
                'title'       => 'IVR System Solutions India | Cloud IVR Provider | RichSol',
                'description' => 'Professional IVR system development for Nashik businesses. Automate call handling, reduce costs & improve customer experience. Custom IVR for hospitals, banks & enterprises in Maharashtra.',
                'keywords'    => 'IVR system Nashik, interactive voice response Maharashtra, IVR development Nashik, call automation system, IVR for hospital Nashik, IVR for bank Maharashtra, voice menu system, call center IVR Nashik, toll free IVR India',
                'canonical'   => '/products/ivr-system',
                'og_image'    => '/og-ivr-system.jpg',
                'h1'          => 'IVR System Development in Nashik & Maharashtra',
                'breadcrumb'  => 'IVR System Solutions',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 11,
                'page_key'    => 'bulkEmail',
                'label'       => 'Bulk Email',
                'title'       => 'Bulk Email Marketing Service India | 98% Inbox Rate | RichSol',
                'description' => 'Professional bulk email marketing in Nashik — newsletters, promotional campaigns & automated drip sequences with high deliverability. Grow your Maharashtra business with email marketing.',
                'keywords'    => 'bulk email Nashik, email marketing Maharashtra, email campaign service Nashik, newsletter service Maharashtra, email marketing agency Nashik, bulk email platform, promotional email Nashik, email automation Maharashtra',
                'canonical'   => '/products/bulk-email',
                'og_image'    => '/og-bulk-email.jpg',
                'h1'          => 'Bulk Email Marketing Services in Nashik, Maharashtra',
                'breadcrumb'  => 'Bulk Email Marketing Services',
            ],
        ];
    }

    // ─── Group: software_service ──────────────────────────────────────────────

    private function softwareServices(): array
    {
        $group      = 'software_service';
        $groupLabel = 'Software Services';

        return [
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 1,
                'page_key'    => 'customSoftwareDevelopment',
                'label'       => 'Custom Software Development',
                'title'       => 'Custom Software Development Company India | Built for You | RichSol',
                'description' => 'Expert custom software development company in Nashik. We build tailored ERP, CRM, inventory, and enterprise software for Maharashtra businesses. 16+ years experience. Free consultation!',
                'keywords'    => 'custom software development Nashik, business software Nashik Maharashtra, ERP development Nashik, CRM software Nashik, inventory management software, enterprise software Nashik, bespoke software development, software for MIDC industries Nashik',
                'canonical'   => '/software-it-services/custom-software-development',
                'og_image'    => '/og-custom-software.jpg',
                'h1'          => 'Custom Software Development in Nashik, Maharashtra',
                'breadcrumb'  => 'Custom Software Development',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 2,
                'page_key'    => 'webDevelopment',
                'label'       => 'Web Development',
                'title'       => 'Web Development Company in Nashik | Professional Website Development',
                'description' => 'Top-rated web development company in Nashik. Fast, SEO-friendly websites built with React, Next.js & modern tech. From business sites to complex portals. Maharashtra\'s trusted web agency.',
                'keywords'    => 'web development company Nashik, website development Nashik Maharashtra, professional web developer Nashik, React Next.js developer Nashik, responsive web design Nashik, SEO-friendly website development, website company Nashik 422002, web portal development Maharashtra',
                'canonical'   => '/software-it-services/web-development',
                'og_image'    => '/og-web-development.jpg',
                'h1'          => 'Web Development Company in Nashik — Fast, SEO-Ready Websites',
                'breadcrumb'  => 'Web Development',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 3,
                'page_key'    => 'mobileAppDevelopment',
                'label'       => 'Mobile App Development',
                'title'       => 'Mobile App Development in Nashik | iOS & Android App Company',
                'description' => 'Native and cross-platform mobile app development in Nashik for iOS & Android. User-friendly apps that drive business growth for Maharashtra companies. Get a free app prototype estimate.',
                'keywords'    => 'mobile app development Nashik, iOS app development Nashik, Android app development Maharashtra, React Native developer Nashik, cross-platform app Nashik, mobile application company Nashik, app developer Maharashtra, Flutter developer Nashik',
                'canonical'   => '/software-it-services/mobile-app-development',
                'og_image'    => '/og-mobile-app.jpg',
                'h1'          => 'Mobile App Development in Nashik — iOS & Android',
                'breadcrumb'  => 'Mobile App Development',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 4,
                'page_key'    => 'uiuxDesign',
                'label'       => 'UI/UX Design',
                'title'       => 'UI/UX Design Services in Nashik | User Experience Design Company',
                'description' => 'Professional UI/UX design services in Nashik. We design intuitive, beautiful digital experiences that convert — for websites, apps & SaaS platforms. Trusted by Maharashtra businesses.',
                'keywords'    => 'UI UX design Nashik, user experience design Maharashtra, interface design Nashik, UX agency Nashik, app design company Nashik, web UI design, user-centered design Maharashtra, product design agency Nashik',
                'canonical'   => '/software-it-services/ui-ux-design',
                'og_image'    => '/og-uiux.jpg',
                'h1'          => 'UI/UX Design Services in Nashik, Maharashtra',
                'breadcrumb'  => 'UI/UX Design',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 5,
                'page_key'    => 'ecommerceSolutions',
                'label'       => 'E-Commerce Solutions',
                'title'       => 'E-Commerce Development in Nashik | Online Store Solutions Maharashtra',
                'description' => 'Complete e-commerce website development in Nashik. Payment gateway integration, inventory management & scalable online stores. Grow your business with a powerful ecommerce platform.',
                'keywords'    => 'ecommerce development Nashik, online store development Maharashtra, ecommerce website Nashik, payment gateway integration Nashik, WooCommerce Shopify developer Nashik, B2B ecommerce Maharashtra, ecommerce solutions Nashik 2025',
                'canonical'   => '/software-it-services/ecommerce-solutions',
                'og_image'    => '/og-ecommerce-solutions.jpg',
                'h1'          => 'E-Commerce Development Solutions in Nashik, Maharashtra',
                'breadcrumb'  => 'E-Commerce Solutions',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 6,
                'page_key'    => 'cloudSolutions',
                'label'       => 'Cloud Solutions',
                'title'       => 'Cloud Computing Services in Nashik | AWS Azure Google Cloud',
                'description' => 'Professional cloud solutions for Nashik businesses — AWS, Azure & Google Cloud migration, deployment & management. Scale your infrastructure securely and cost-effectively in Maharashtra.',
                'keywords'    => 'cloud computing Nashik, AWS Azure Google Cloud Nashik, cloud migration Maharashtra, cloud services company Nashik, cloud hosting Nashik, cloud deployment Maharashtra, cloud infrastructure management, SaaS PaaS IaaS Nashik',
                'canonical'   => '/software-it-services/cloud-solutions',
                'og_image'    => '/og-cloud.jpg',
                'h1'          => 'Cloud Computing Services in Nashik — AWS, Azure & More',
                'breadcrumb'  => 'Cloud Solutions',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 7,
                'page_key'    => 'apiIntegration',
                'label'       => 'API Integration',
                'title'       => 'API Integration Services in Nashik | Custom API Development',
                'description' => 'Expert API integration and custom API development in Nashik. Connect your apps with payment gateways, CRMs, ERPs & third-party services. Robust REST APIs for Maharashtra businesses.',
                'keywords'    => 'API integration Nashik, REST API development Maharashtra, custom API Nashik, third-party API integration, API developer Nashik, web services integration, payment gateway API Nashik, CRM API integration Maharashtra',
                'canonical'   => '/software-it-services/api-integration',
                'og_image'    => '/og-api.jpg',
                'h1'          => 'API Integration & Custom API Development in Nashik',
                'breadcrumb'  => 'API Integration',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 8,
                'page_key'    => 'maintenanceSupport',
                'label'       => 'Maintenance & Support',
                'title'       => 'Software Maintenance & Support Services in Nashik | Annual AMC',
                'description' => 'Reliable software maintenance, bug fixes & technical support for Nashik businesses. Annual AMC plans, 24/7 support options & performance optimization for all software platforms.',
                'keywords'    => 'software maintenance Nashik, technical support Maharashtra, software AMC Nashik, bug fixing service Nashik, software update service, application support Maharashtra, IT support company Nashik, website maintenance Nashik',
                'canonical'   => '/software-it-services/maintenance-support',
                'og_image'    => '/og-maintenance.jpg',
                'h1'          => 'Software Maintenance & Support in Nashik — Annual AMC Plans',
                'breadcrumb'  => 'Maintenance & Support',
            ],
        ];
    }

    // ─── Group: digital_marketing_service ─────────────────────────────────────

    private function digitalMarketingServices(): array
    {
        $group      = 'digital_marketing_service';
        $groupLabel = 'Digital Marketing Services';

        return [
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 1,
                'page_key'    => 'seoServices',
                'label'       => 'SEO Services',
                'title'       => 'SEO Services in Nashik, Maharashtra | Search Engine Optimization',
                'description' => 'Professional SEO services in Nashik to rank #1 on Google. On-page, off-page, technical SEO & local SEO for Maharashtra businesses. Transparent reporting & proven results. Free audit!',
                'keywords'    => 'SEO services Nashik, search engine optimization Maharashtra, SEO company Nashik, local SEO Nashik, Google ranking Nashik, organic search Maharashtra, SEO agency Nashik, keyword optimization, website ranking Nashik, technical SEO Maharashtra',
                'canonical'   => '/digital-marketing-services/seo',
                'og_image'    => '/og-seo.jpg',
                'h1'          => 'SEO Services in Nashik — Rank #1 on Google',
                'breadcrumb'  => 'SEO Services',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 2,
                'page_key'    => 'socialMediaMarketing',
                'label'       => 'Social Media Marketing',
                'title'       => 'Social Media Marketing in Nashik | Facebook Instagram LinkedIn Ads',
                'description' => 'Expert social media marketing agency in Nashik. Grow your brand on Facebook, Instagram & LinkedIn with compelling content, paid ads & community management. Serving Maharashtra businesses.',
                'keywords'    => 'social media marketing Nashik, SMM agency Nashik Maharashtra, Facebook marketing Nashik, Instagram marketing Nashik, LinkedIn marketing Maharashtra, social media management Nashik, social media advertising Nashik, brand building social media',
                'canonical'   => '/digital-marketing-services/social-media-marketing',
                'og_image'    => '/og-smm.jpg',
                'h1'          => 'Social Media Marketing Agency in Nashik, Maharashtra',
                'breadcrumb'  => 'Social Media Marketing',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 3,
                'page_key'    => 'ppcAdvertising',
                'label'       => 'PPC Advertising',
                'title'       => 'PPC Advertising in Nashik | Google Ads & Facebook Ads Management',
                'description' => 'Drive targeted traffic with PPC advertising in Nashik. Expert Google Ads, Facebook Ads & Instagram Ads management with measurable ROI for Maharashtra businesses. Free account audit!',
                'keywords'    => 'PPC advertising Nashik, Google Ads management Nashik, Facebook Ads Nashik Maharashtra, pay per click Nashik, paid advertising agency Nashik, ad campaign management Maharashtra, search ads Nashik, display advertising Maharashtra',
                'canonical'   => '/digital-marketing-services/ppc-advertising',
                'og_image'    => '/og-ppc.jpg',
                'h1'          => 'PPC Advertising Services in Nashik — Google & Facebook Ads',
                'breadcrumb'  => 'PPC Advertising',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 4,
                'page_key'    => 'contentMarketing',
                'label'       => 'Content Marketing',
                'title'       => 'Content Marketing Services in Nashik | Blogs, Copywriting & Strategy',
                'description' => 'Strategic content marketing for Nashik businesses — SEO blog writing, website copywriting, product descriptions & content strategy. Build authority and generate leads with quality content.',
                'keywords'    => 'content marketing Nashik, blog writing Maharashtra, SEO content writing Nashik, copywriting services Maharashtra, content strategy Nashik, website content writing, article writing service Nashik, content marketing agency Maharashtra',
                'canonical'   => '/digital-marketing-services/content-marketing',
                'og_image'    => '/og-content.jpg',
                'h1'          => 'Content Marketing Services in Nashik — Blogs, Copy & Strategy',
                'breadcrumb'  => 'Content Marketing',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 5,
                'page_key'    => 'emailMarketing',
                'label'       => 'Email Marketing',
                'title'       => 'Email Marketing Services in Nashik | Campaign Management & Automation',
                'description' => 'Professional email marketing services in Nashik — targeted campaigns, newsletter management & email automation. High deliverability, detailed analytics. Grow your Maharashtra business.',
                'keywords'    => 'email marketing Nashik, email campaign management Maharashtra, newsletter service Nashik, email automation Nashik, drip campaign Maharashtra, email marketing agency Nashik, bulk email marketing, email marketing platform Nashik',
                'canonical'   => '/digital-marketing-services/email-marketing',
                'og_image'    => '/og-email-marketing.jpg',
                'h1'          => 'Email Marketing Services in Nashik, Maharashtra',
                'breadcrumb'  => 'Email Marketing',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 6,
                'page_key'    => 'whatsappMarketing',
                'label'       => 'WhatsApp Marketing',
                'title'       => 'WhatsApp Marketing in Nashik | Official Meta Verified API Solutions',
                'description' => 'Boost customer engagement with WhatsApp marketing in Nashik. Send promotions, updates & campaigns via official Meta Verified WhatsApp Business API. Best WhatsApp marketing provider Maharashtra.',
                'keywords'    => 'WhatsApp marketing Nashik, WhatsApp Business API Maharashtra, bulk WhatsApp messages Nashik, WhatsApp campaign service, Meta verified WhatsApp Nashik, WhatsApp promotional messages, WhatsApp customer engagement Maharashtra, official WhatsApp marketing India',
                'canonical'   => '/digital-marketing-services/whatsapp-marketing',
                'og_image'    => '/og-whatsapp-marketing.jpg',
                'h1'          => 'WhatsApp Marketing Services in Nashik — Meta Verified API',
                'breadcrumb'  => 'WhatsApp Marketing',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 7,
                'page_key'    => 'bulkSMSMarketing',
                'label'       => 'Bulk SMS Marketing',
                'title'       => 'Bulk SMS Marketing Services in Nashik | SMS Campaigns for Businesses',
                'description' => 'Professional bulk SMS marketing in Nashik for promotional & transactional campaigns. High open rates, instant delivery, detailed reports. Best bulk SMS provider in Maharashtra.',
                'keywords'    => 'bulk SMS marketing Nashik, SMS campaign Maharashtra, promotional SMS Nashik, transactional SMS service, text marketing Nashik, SMS marketing agency Maharashtra, bulk SMS for business, SMS advertising Nashik',
                'canonical'   => '/digital-marketing-services/bulk-sms',
                'og_image'    => '/og-bulk-sms-marketing.jpg',
                'h1'          => 'Bulk SMS Marketing Services in Nashik, Maharashtra',
                'breadcrumb'  => 'Bulk SMS Marketing',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 8,
                'page_key'    => 'graphicDesignDM',
                'label'       => 'Graphic Design',
                'title'       => 'Graphic Design Agency in Nashik | Logo, Branding & Creative Design',
                'description' => 'Creative graphic design agency in Nashik — logo design, brand identity, social media creatives & marketing collateral. Professional designers delivering stunning visuals for Maharashtra businesses.',
                'keywords'    => 'graphic design Nashik, logo design agency Nashik, branding agency Maharashtra, creative design Nashik, social media design, marketing collateral design, brand identity Nashik, print design Nashik, digital design Maharashtra',
                'canonical'   => '/digital-marketing-services/graphic-design',
                'og_image'    => '/og-graphic-design-service.jpg',
                'h1'          => 'Graphic Design Agency in Nashik — Logo, Branding & Creatives',
                'breadcrumb'  => 'Graphic Design',
            ],
            [
                'group' => $group, 'group_label' => $groupLabel, 'order' => 9,
                'page_key'    => 'videoMarketing',
                'label'       => 'Video Marketing',
                'title'       => 'Video Marketing Services in Nashik | Promotional Videos & Reels',
                'description' => 'Professional video marketing in Nashik — promotional videos, social media reels, explainer animations & product demos. Engage your audience and boost conversions with compelling video content.',
                'keywords'    => 'video marketing Nashik, promotional video Nashik Maharashtra, social media reels production, explainer video Nashik, animated video service, video production agency Nashik, YouTube video marketing, Instagram reels Nashik',
                'canonical'   => '/digital-marketing-services/video-marketing',
                'og_image'    => '/og-video-marketing.jpg',
                'h1'          => 'Video Marketing Services in Nashik — Reels, Promos & Animations',
                'breadcrumb'  => 'Video Marketing',
            ],
        ];
    }
}
